# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "enem_db"

  cluster:
    user: root
    build: .
    image: pyspark
    working_dir: /app
    volumes:
      - .:/app
